### ISSUE TITLE
disable x-select-enable-primary 

### ISSUE THREAD

**Issue by izahn** [technomancy/better-defaults#22]
I'm curious what the advantage of `x-select-enable-primary`  is. It breaks selecting a region and yanking to replace it with `delete-selection-mode` turned on. Perhaps leave it off?

**Comment by technomancy** [comment]
Yes, this was due to a misunderstanding and an unclear docstring.

This variable only changes the behavior of yanking into Emacs; contrary
to the docstring you can still interact with the primary selection when
pasting outside Emacs even when it's not set.
