### ISSUE TITLE
If ivy-mode is enabled, don't set ido-mode

### ISSUE THREAD

**Issue by tomfitzhenry** [technomancy/better-defaults#24]
Setting ido-mode remaps C-x C-f from find-file to ido-find-file.

ivy users typically don't want C-x C-f to be remapped from find-file to ido-find-file, since for an ivy user find-file has sensible behaviour. ivy-mode manages to improve find-file by reimplementing `completing-read-function`, which is called by `find-file`, rather than reimplementing `find-file`.

In the same way that better-defaults doesn't set ido-mode if helm-mode is defined, ideally it wouldn't set ido-mode if ivy-mode is defined.

**Comment by tmtvl** [comment]
As #28 has been merged, I think this issue can be closed.

**Comment by technomancy** [comment]
Good call; thanks.
