### ISSUE TITLE
make compatible with no-littering.el

### ISSUE THREAD

**Issue by gonewest818** [technomancy/better-defaults#35]
I'm testing out the [no-littering.el](https://github.com/emacscollective/no-littering) package, which asks to be placed "as early as possible" in my `init.el`.  Having done that, however, I see `save-place-file` and `backup-directory-alist` are subsequently overwritten by `better-defaults`.

What I'd like to suggest is for this package to check if `no-littering` is in play, and if so, then don't override these (or any) path variables because they're already set how `no-littering` wants.  Granted, I could also just initialize `no-littering` after `better-defaults`.

**Comment by technomancy** [comment]
> What I'd like to suggest is for this package to check if
> `no-littering` is in play, and if so, then don't override these (or
> any) path variables because they're already set how `no-littering`
> wants.

I think we can actually remove the save-place-file setting; the default
value used to be bad, but in 25 it's got a reasonable default.

For backup-directory-alist I think we should just set it if it's nil and
leave it alone otherwise.

**Comment by gonewest818** [comment]
Sounds good to me. I can make the change and submit a PR.
