### ISSUE TITLE
Feature Request: Quick-Start Instructions

### ISSUE THREAD

**Issue by kurtismullins** [technomancy/better-defaults#6]
In the README file, there appears to be no instructions on how to use this particular package. I am *sure* many can figure it out with a bit of Google-fu ... but as a Starter Package, it would be great to have some quick-start instructions to jump right in.

----

**Example:**

1. Fork this repository. 
2. Create a local folder called `~/.emacs.d/`. 
3. Clone this repository into that folder.
4. Happy Hacking!

-----

*Note:* I'm sure someone can come up with better instructions than that. I also have no clue whether or not those directions sound anywhere near sane :)

**Comment by technomancy** [comment]
@sumitsahrawat Thanks; somehow I was unsubscribed, probably due to the way GitHub binds keystrokes that conflict with a bunch of my own browser settings.

I have added a note to the readme that installing this package is all that's necessary to use it.
